apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-2
  namespace: dev-manifest # added namespace field
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
